---

 - name: I think I am installing in RedHat. Print where I am Installing!!!
   debug:
     msg: "{{ansible_hostname}} {{ansible_os_family}} install_type={{install_type}} install_host={{install_host}}"
   when:
     - ansible_os_family == "RedHat"

 - name: Ensure "{{user}}" group is present
   group:
     name: "{{user}}"
     state: present

 - name: figure out who I am
   command: whoami
   register: whoami

 - name: show who I am
   debug:
     msg: "I am {{whoami.stdout}}"

 - name: Creates directory "{{unzip_home_bw6_files}}"
   file: 
     path:  "{{unzip_home_bw6_files}}"
     owner: "{{user}}" 
     group: "{{user}}" 
     mode: 0755 
     state: directory

    
 - name: unzip "{{install_media_bw6_files}}" to "{{unzip_home_bw6_files}}"
   unarchive:
      src: "{{install_media_bw6_files}}"
      dest: "{{unzip_home_bw6_files}}"
      remote_src: no
   

 - name: Replace config params in BW6 silent file "{{unzip_home_bw6_files}}{{silent_report_bw6_files}}" for installationRoot
   replace:
       dest="{{unzip_home_bw6_files}}{{silent_report_bw6_files}}"
       regexp='<entry key="installationRoot">/opt/tibco/bw</entry>'
       replace='<entry key="installationRoot">{{tib_home}}</entry>'
       backup=yes

 - name: Replace config params in BW6 silent file "{{unzip_home_bw6_files}}{{silent_report_bw6_files}}" for configDirectoryRoot
   replace:
       dest="{{unzip_home_bw6_files}}{{silent_report_bw6_files}}"
       regexp='<entry key="configDirectoryRoot">/opt/tibco/bw</entry>'
       replace='<entry key="configDirectoryRoot">{{tib_config_home}}</entry>'
       backup=yes

 - name: Replace config params in BW6 silent file "{{unzip_home_bw6_files}}{{silent_report_bw6_files}}" for "{{tib_environment}}"
   replace:
       dest="{{unzip_home_bw6_files}}{{silent_report_bw6_files}}"
       regexp='bw6'
       replace='{{tib_environment}}'
       backup=yes

 - name: Run BW6 files plugin silent install using "{{unzip_home_bw6_files}}{{installer}} -silent"
   command: "{{unzip_home_bw6_files}}{{installer}} -silent"
   args:
      chdir: "{{unzip_home_bw6_files}}"
      

