---

 - name: I think I am installing in RedHat. Print where I am Installing!!!
   debug:
     msg: "{{ansible_hostname}} {{ansible_os_family}} install_type={{install_type}} install_host={{install_host}}"
   when:
     - ansible_os_family == "RedHat"

 - name: Ensure "{{user}}" group is present
   group:
     name: "{{user}}"
     state: present

 - name: figure out who I am
   command: whoami
   register: whoami

 - name: show who I am
   debug:
     msg: "I am {{whoami.stdout}}"

 - name: Creates directory "{{unzip_home_hawk}}"
   file: 
     path:  "{{unzip_home_hawk}}"
     owner: "{{user}}" 
     group: "{{user}}" 
     mode: 0755 
     state: directory

 - name: Creates directory "{{tib_home}}"
   file: 
     path:  "{{tib_home}}"
     owner: "{{user}}" 
     group: "{{user}}" 
     mode: 0755 
     recurse: yes
     state: directory
   become_user: root



# Hawk Install
        
 - name: unzip "{{install_media_hawk}}"  to "{{unzip_home_hawk}}"
   unarchive:
      src: "{{install_media_hawk}}"
      dest: "{{unzip_home_hawk}}"
      remote_src: no

 - name: Replace config params in HAWK silent file "{{unzip_home_hawk}}{{silent_report_hawk}}" for /home/user/tibco
   replace:
       dest="{{unzip_home_hawk}}{{silent_report_hawk}}"
       regexp='/home/user/tibco'
       replace='{{tib_config_home}}'
       backup=yes

 - name: Replace config params in HAWK silent file "{{unzip_home_hawk}}{{silent_report_hawk}}" for /opt/tibco
   replace:
       dest="{{unzip_home_hawk}}{{silent_report_hawk}}"
       regexp='/opt/tibco'
       replace='{{tib_home}}'
       backup=yes

 - name: Replace JDK params in HAWK silent file "{{unzip_home_hawk}}{{silent_report_hawk}}" for /opt/java/jdk1.7.0_71
   replace:
       dest="{{unzip_home_hawk}}{{silent_report_hawk}}"
       regexp='/opt/tibco/Java/jdk1.7.0_09'
       replace='{{jdk_home}}'
       backup=yes

 - name: Replace config params in HAWK silent file "{{unzip_home_hawk}}{{silent_report_hawk}}" for "{{tib_environment}}"
   replace:
       dest="{{unzip_home_hawk}}{{silent_report_hawk}}"
       regexp='TIBCO-HAWK-HOME'
       replace='{{tib_environment}}'
       backup=yes
       
 - name: Replace config params in HAWK silent file "{{unzip_home_hawk}}{{silent_report_hawk}}" for "{{tomcatPort}}"
   replace:
       dest="{{unzip_home_hawk}}{{silent_report_hawk}}"
       regexp='8080'
       replace='{{tomcatPort}}'
       backup=yes
       
 - name: Replace config params in HAWK silent file "{{unzip_home_hawk}}{{silent_report_hawk}}" for "{{tomcatShutdownPort}}"
   replace:
       dest="{{unzip_home_hawk}}{{silent_report_hawk}}"
       regexp='8081'
       replace='{{tomcatShutdownPort}}'
       backup=yes

 - name: Run HAWK silent install using "{{unzip_home_hawk}}{{installer}} -silent"
   command: "{{unzip_home_hawk}}{{installer}} -silent"
   args:
      chdir: "{{unzip_home_hawk}}"


# Hawk Install HF--002
 - name: Creates directory "{{unzip_home_hawk_hf}}"
   file: 
     path:  "{{unzip_home_hawk_hf}}"
     owner: "{{user}}" 
     group: "{{user}}" 
     mode: 0755 
     state: directory
     
 - name: unzip "{{install_media_hawk_hf}}"  to "{{unzip_home_hawk_hf}}"
   unarchive:
      src: "{{install_media_hawk_hf}}"
      dest: "{{unzip_home_hawk_hf}}"
      remote_src: no

 - name: Copy from "{{unzip_home_hawk}}{{silent_report_hawk}}" to "{{unzip_home_hawk_hf}}{{silent_report_hawk_hf}}"
   copy:
       src: "{{unzip_home_hawk}}{{silent_report_hawk}}"
       dest: "{{unzip_home_hawk_hf}}{{silent_report_hawk_hf}}"
       remote_src: yes
       backup: yes

 - name: Copy from "{{unzip_home_hawk}}{{installer}}" to "{{unzip_home_hawk_hf}}"
   copy:
       src: "{{unzip_home_hawk}}{{installer}}"
       dest: "{{unzip_home_hawk_hf}}"
       remote_src: yes
       backup: no
       mode: 0755

 - name: Run HAWK silent install using "{{unzip_home_hawk_hf}}{{installer}} -silent"
   command: "{{unzip_home_hawk_hf}}{{installer}} -silent"
   args:
      chdir: "{{unzip_home_hawk_hf}}"